# -*- coding: utf-8 -*-
"""Calculate mean and variance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFVjBhemFJPBBkQ_9qcDIT0b7e44tK-_
"""

import numpy as np
import pandas as pd

data= [10.4,20,7,14.7,21.2]

def calculate_mean(data):
  m1= sum(data)/len(data)
  return m1
data= [10.4,20,7,14.7,21.2]
m1= calculate_mean(data)
print("Mean is:", m1)

def calculate_variance(data):
  mean= calculate_mean(data)
  variance= (sum((x-mean)**2 for x in data)/len(data))
  return round(variance)

data= [10.4,20,7,14.7,21.2]
v1= calculate_variance(data)
print("Variance is:",v1)

mean= np.mean(data)
variance= np.var(data).round(2)
std= np.std(data).round(2)
print("Mean is: " , mean)
print("Variance is:", variance)
print("Standard Daviation is:", std)