# -*- coding: utf-8 -*-
"""Encode Categorical data into Numerical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFVjBhemFJPBBkQ_9qcDIT0b7e44tK-_
"""

import numpy as np
import pandas as pd

data= pd.DataFrame({
    'Food':['Icecream','Darkchocolate','Pizza','Posto'],
    'Fruit':['Orange','Apple','Banana','Mango']
})

"""#Lebel Encoding"""

!pip install LebelEncoder

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

data['Food_Encoded']=le.fit_transform(data['Food'])
data['Fruit_Encoded']=le.fit_transform(data['Fruit'])

print(data)

"""#Using One-Hot-Encoding"""

from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

data_ohe= pd.get_dummies(data[['Food','Fruit']],dtype=int)

print(data_ohe)

