# -*- coding: utf-8 -*-
"""Handling missing values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFVjBhemFJPBBkQ_9qcDIT0b7e44tK-_
"""

import numpy as np
import pandas as pd

data= pd.DataFrame({
    'f1':[20,10,np.nan,40,np.nan],
    'f2':[100,200,np.nan,400,500]
})

"""#Missing values fill with mean"""

data1= data.fillna(data.mean().round(2)).round(2)
print(data1)

"""#Missing values fill with median"""

data2=data.fillna(data.median()).round(2)
print(data2)

"""#Fill with interpolation(Good for time series data)"""

data3= data.fillna(data.interpolate())
print(data3)

"""#Fill with constant and Domain value"""

data4= data.fillna({'f1':100,'f2':500})
print(data4)

"""#Drop rows with missing values"""

data5= data.dropna()
print(data5)

