# -*- coding: utf-8 -*-
"""Max-min-scaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFVjBhemFJPBBkQ_9qcDIT0b7e44tK-_
"""

import numpy as np
import pandas as pd

def max_min_normalization(df):
  return (df-df.min())/(df.max() - df.min())

data =pd.DataFrame({
    'f1':[10,20,30,40],
    'f2':[40,50,60,70]
})

normalised_data = max_min_normalization(data)
print(normalised_data)