# -*- coding: utf-8 -*-
"""Standardize using z-score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFVjBhemFJPBBkQ_9qcDIT0b7e44tK-_
"""

import numpy as np
import pandas as pd

def z_score(df):
  return (df - df.mean()/df.std())

data =pd.DataFrame({
    'f1':[10,20,30,40],
    'f2':[5,15,25,35]
})

standardized_data = z_score(data)
print(standardized_data)